Fix managing projects configs via Salt
Managing gerrit projects via Salt is broken because jeepyb creating
commit and tries to push this commit to "refs/meta/config", but getting
error: (invalid committer)

2017-09-19 07:23:18,527: jeepyb.utils - DEBUG - Command said: remote:
^Mremote: Processing changes: refs: 1        ^Mremote: Processing
changes: refs: 1, done
remote:
remote: ERROR:  In commit d077aeb08a20c1e8ee05fa78220dcd71c7b3a3b6
remote: ERROR:  committer email address
root@cid01.pilot.mcp.jiocloud.com
remote: ERROR:  does not match your user account.
remote: ERROR:
remote: ERROR:  The following addresses are currently registered:
remote: ERROR:    root@localhost
remote: ERROR:
remote: ERROR:  To register an email address, please visit:
remote: ERROR:  http://10.147.204.90:8080/#/settings/contact
remote:
remote:
To ssh://10.147.204.90:29418/openstack/glance
 ! [remote rejected] HEAD -> refs/meta/config (invalid committer)

GIT_COMMITTER_EMAIL in environment variables fixing this issue.

Additional logs: https://pastebin.com/raw/AuGrxPsF

Change-Id: I6cd7acc2f300da495d80b070f54554921c70b319